---
  - hosts: control-plane
    name: "Bootstrap Kubernetes Control Plane"
    roles:
      - name: kubeadm init
        role: kubeadm-init

      - name: install calico
        role: calico
    tasks:
      - name: configure local user
        shell:  |
           mkdir -p ~/.kube
           pwd
           sudo pwd
           sudo echo $(id -u):$(id -g)
           sudo cp /etc/kubernetes/admin.conf ~/.kube/config
           sudo chown $(id -u):$(id -g) ~/.kube/config
        become: no